/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment_2;

import javax.swing.*;

/**
 *
 * @author aj132
 */
public class UseSavingBankAcount extends javax.swing.JFrame {

    boolean bmRb1;
    boolean bmRb2;
    boolean bmRb3;
    SavingAccount[] accountList = new SavingAccount[50];
    /**
     * Creates new form UseSavingBankAcount
     */
    public UseSavingBankAcount() {
        initComponents();
        
        //create button group for radio buttons
        ButtonGroup group = new ButtonGroup();
        group.add(rB1AccountInfoC);
        group.add(rB2AccountInfoS);
        group.add(rB3LoanAmount);
        
        //set button values to false by default
        bmRb1 = false;
        bmRb2 = false;
        bmRb3 = false;
        
        boolean isSavings = false;
        char type = 'C';
        
        for(int lcv = 0; lcv < accountList.length; lcv++) {
           
            accountList[lcv] = new SavingAccount(0.07 , "TTU"+ lcv, 100 + lcv , type);
            
            //toggles type between 'C' and 'S' on every iteration
            //of the loop
            if(isSavings) {
                type = 'C';
                isSavings = false;
            }
            else {
                type = 'S';
                isSavings = true;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rB1AccountInfoC = new javax.swing.JRadioButton();
        rB3LoanAmount = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        rB2AccountInfoS = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rB1AccountInfoC.setText("Display account holder information (Checking)");
        rB1AccountInfoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rB1AccountInfoCActionPerformed(evt);
            }
        });

        rB3LoanAmount.setText("Deduct loan amount");
        rB3LoanAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rB3LoanAmountActionPerformed(evt);
            }
        });

        submitButton.setText("Gimme");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        rB2AccountInfoS.setText("Display account holder information (Savings)");
        rB2AccountInfoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rB2AccountInfoSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitButton)
                    .addComponent(rB1AccountInfoC)
                    .addComponent(rB3LoanAmount)
                    .addComponent(rB2AccountInfoS))
                .addContainerGap(490, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(rB1AccountInfoC)
                .addGap(29, 29, 29)
                .addComponent(rB2AccountInfoS)
                .addGap(27, 27, 27)
                .addComponent(rB3LoanAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rB1AccountInfoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rB1AccountInfoCActionPerformed
        // TODO add your handling code here:
        bmRb1 = true;
        bmRb2 = false;
        bmRb3 = false;
    }//GEN-LAST:event_rB1AccountInfoCActionPerformed
    
    private void rB3LoanAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rB3LoanAmountActionPerformed
        // TODO add your handling code here:
        bmRb1 = false;
        bmRb2 = false;
        bmRb3 = true;
    }//GEN-LAST:event_rB3LoanAmountActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        if(bmRb1) {
            //display Account Information
            this.displayAllByAccountType(accountList,'C');
        }
        else if(bmRb2) {
            this.displayAllByAccountType(accountList,'S');
        }
        else if(bmRb3) {
            //loan ammount shit
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void rB2AccountInfoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rB2AccountInfoSActionPerformed
        // TODO add your handling code here:
        bmRb1 = false;
        bmRb2 = true;
        bmRb3 = false;
    }//GEN-LAST:event_rB2AccountInfoSActionPerformed
    
    public void displayAllByAccountType(SavingAccount[] objArray, char type) {
        objArray = sortByBalance(objArray);
        
        
    }
    
    public SavingAccount[] sortByBalance(SavingAccount[] objArray) {
        
        return objArray;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton rB1AccountInfoC;
    private javax.swing.JRadioButton rB2AccountInfoS;
    private javax.swing.JRadioButton rB3LoanAmount;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
